name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13"
      - name: Run tests
        run: go test ./pkg/...
      - name: Update codecov
        run: bash <(curl -s https://codecov.io/bash)
