name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./pkg/... -coverprofile cover.out.tmp
      - name: Removes mocks from tests
        run: cat cover.out.tmp | grep -v "_mock.go" > cover.out
      - uses: codecov/codecov-action@v1
        with:
          file: ./cover.out
      - name: Update codecov
        run: bash <(curl -s https://codecov.io/bash)
